/**
 * All user-facing copy in one place.
 * In Phase 4, replace values with t('key') from i18next — the key structure
 * here maps directly to the i18n namespace/key hierarchy.
 */
export const Copy = {
  app: {
    name: 'BG Ape',
  },
  auth: {
    signIn: 'Sign in',
    signUp: 'Create account',
    signOut: 'Sign out',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    forgotPassword: 'Forgot password?',
    noAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    resetEmailSent: 'Password reset email sent.',
  },
  chat: {
    inputPlaceholder: 'Ask about a game…',
    sendButton: 'Send',
    emptyState: 'Ask for a game recommendation or a quick-start rules guide.',
    sending: 'Sending…',
    errorRetry: 'Tap to retry',
    starters: [
      'Recommend a game for 4 players',
      'What should we play tonight?',
      'Give me quick rules for a party game',
    ],
    clearConversation: 'Clear',
    clearConfirmTitle: 'Clear conversation',
    clearConfirmBody: 'Delete all messages in this conversation? This cannot be undone.',
    deleteMessageTitle: 'Delete message',
    deleteMessageBody: 'Delete this message?',
    delete: 'Delete',
    cancel: 'Cancel',
    conversations: {
      title: 'Conversations',
      empty: 'No conversations yet. Start one below.',
      newButton: '+ New conversation',
      newTitle: 'Start a conversation',
      reasonLabel: 'What do you need?',
      gameLabel: 'About a game? (optional)',
      noGame: 'No specific game',
      create: 'Start',
      deleteTitle: 'Delete conversation',
      deleteBody: 'Delete this conversation and all its messages?',
      untitled: 'Untitled',
    },
    reasons: {
      recommendation: 'Help me pick a game',
      setup: 'Quick setup',
      rules: 'Rules help',
      general: 'General chat',
    },
  },
  collection: {
    title: 'My Collection',
    empty: 'No games yet. Tap + to search BoardGameGeek and add your first game.',
    addPlaceholder: 'Game name…',
    addButton: 'Add game',
    addTitle: 'Add a game',
    searchPlaceholder: 'Search BoardGameGeek…',
    noResults: 'No games found on BoardGameGeek.',
    addManually: (q: string) => `Add "${q}" manually`,
    remove: 'Remove',
    removeConfirmTitle: 'Remove game',
    removeConfirmBody: 'Remove this game from your collection?',
    cancel: 'Cancel',
    countLabel: (n: number) => `${n} ${n === 1 ? 'game' : 'games'}`,
    playsLabel: (n: number) => `${n} ${n === 1 ? 'play' : 'plays'}`,
    ownedSince: (date: string) => `Owned since ${date}`,
    rankLabel: (n: number) => `BGG #${n}`,
    playersLabel: (min?: number, max?: number) => {
      if (min === undefined && max === undefined) return '';
      if (min !== undefined && max !== undefined && min !== max) return `${min}–${max} players`;
      const n = min ?? max;
      return `${n} players`;
    },
  },
  gameDetail: {
    playersLabel: 'Players',
    playTimeLabel: 'Play time',
    weightLabel: 'Complexity',
    ratingLabel: 'BGG rating',
    rankLabel: 'BGG rank',
    playsLabel: 'Your plays',
    statsTitle: 'Stats',
    notesTitle: 'My notes',
    notesPlaceholder: 'Add your own notes about this game…',
    remove: 'Remove from collection',
    minutes: (n: number) => `${n} min`,
    weightValue: (n: number) => `${n.toFixed(1)} / 5`,
    ratingValue: (n: number) => `${n.toFixed(1)} / 10`,
    notFound: 'Game not found.',
    dash: '—',
    categoriesTitle: 'Categories & Mechanics',
    playsHistoryTitle: 'Play history',
    noPlaysYet: 'No plays recorded yet.',
  },
  tabs: {
    home: 'Home',
    chat: 'Chat',
    collection: 'Collection',
    account: 'Account',
  },
  home: {
    greeting: 'Welcome to BG Ape',
    subtitle: 'Your board-game night, sorted.',
    askAnything: 'Ask BG Ape anything',
    askHint: 'Recommendations, rules, setup — just ask.',
    iWant: 'I want to…',
    actionHints: {
      recommendation: "Tell me who's playing and I'll suggest the perfect game.",
      setup: 'Skip the manual — get a game set up in minutes.',
      rules: 'Ask about any rule and get a clear answer.',
      general: 'Just chat about board games.',
    },
    activityTitle: 'Your activity',
    topGamesTitle: 'Top games',
    logPlay: '+ Log a play',
    seeAll: 'See all',
    noActivity: 'No plays logged yet. Once you log games, your activity shows here.',
    noGames: 'No games yet. Add some to your collection.',
  },
  plays: {
    title: 'Plays',
    logButton: '+ Log a play',
    empty: 'No plays logged yet. Tap "Log a play" to record your first game.',
    formTitle: 'Log a play',
    gameLabel: 'Game',
    gamePlaceholder: 'Type a game name…',
    fromCollection: 'From your collection',
    dateLabel: 'Date',
    today: 'Today',
    yesterday: 'Yesterday',
    datePlaceholder: 'YYYY-MM-DD',
    locationLabel: 'Location',
    locationPlaceholder: 'e.g. Home, Café Meeple',
    playersLabel: 'Players',
    durationLabel: 'Duration (min)',
    noteLabel: 'Note',
    notePlaceholder: 'Add a note…',
    noteRowPlaceholder: 'Add note…',
    save: 'Save play',
    cancel: 'Cancel',
    delete: 'Delete',
    deleteTitle: 'Delete play',
    deleteBody: 'Delete this logged play?',
    invalidDate: 'Use the format YYYY-MM-DD.',
    playersShort: (n: number) => `${n}p`,
    durationShort: (n: number) => `${n}m`,
  },
  stats: {
    title: 'Stats',
    metricPlays: 'Plays',
    metricGroup: 'Group size',
    rangeDay: 'Day',
    rangeWeek: 'Week',
    rangeMonth: 'Month',
    empty: 'No activity yet. Log some plays to see your stats.',
  },
  account: {
    title: 'Account',
    displayNameLabel: 'Display name',
    gamingNickLabel: 'Gaming nickname',
    gamingNickPlaceholder: 'e.g. MeepleMaster',
    emailLabel: 'Email',
    saveButton: 'Save changes',
    editProfile: 'Edit profile',
    profileUpdated: 'Profile updated.',
    integrationsTitle: 'Integrations',
    integrationsSubtitle: 'Connect your gaming accounts to unlock more.',
    comingSoon: 'Coming soon',
  },
  intent: {
    backButton: '‹',
    startButton: 'Start conversation',
    promptPreviewLabel: 'Your question (edit if needed)',
    promptPlaceholder: 'Fill in the filters above to build your question…',

    gamePicker: {
      title: 'Help me pick a game',
      fromCollectionLabel: 'From my collection',
      fromCollectionHint: 'Limits suggestions to games you own',
      playersLabel: 'Players',
      complexityLabel: 'Complexity',
      complexityOptions: ['Low', 'Medium', 'High'] as const,
      playTimeLabel: 'Play time (min)',
      playTimeOptions: ['15', '30', '60', '120', '120+'] as const,
      categoryLabel: 'Category / Mechanics (pick any)',
      categoryOptions: [
        'Deck building',
        'Strategy',
        'Competitive',
        'Cooperative',
        'Euro',
        'Story',
      ] as const,
      tableSizeLabel: 'Table space available',
      tableSizeOptions: ['Pocket', 'S', 'M', 'L'] as const,
      notesLabel: 'Anything else?',
      notesPlaceholder: 'e.g. kids-friendly, no reading…',
      promptParts: {
        intro: 'Help me pick a board game to play.',
        players: (n: string) => `We are ${n} players.`,
        complexity: (c: string) => `Preferred complexity: ${c}.`,
        playTime: (t: string) => `Available time: ${t} minutes.`,
        categories: (cs: string[]) => `Preferred mechanics/genre: ${cs.join(', ')}.`,
        tableSize: (s: string) => `Table space available: ${s}.`,
        fromCollection: 'Please suggest only from my collection.',
        notes: (s: string) => s,
      },
    },

    quickSetup: {
      title: 'Quick setup guide',
      fromCollectionLabel: 'From my collection',
      collectionDropdownPlaceholder: 'Pick a game…',
      gameNamePlaceholder: 'Type a game name…',
      depthLabel: 'How deep should we go?',
      depthOptions: [
        { id: 'quick', label: 'Start and go — 5 minutes' },
        { id: 'basic', label: 'Understand the basics — 15 minutes' },
        { id: 'full', label: 'Full rules walkthrough' },
      ] as const,
      promptParts: {
        intro: (game: string) => (game ? `Quick setup guide for ${game}.` : 'Quick setup guide.'),
        depth: {
          quick: 'Give me just enough to start playing right now (5 minutes).',
          basic: 'Walk me through the core rules so we understand the basics (15 minutes).',
          full: 'Give me a complete rules walkthrough.',
        } as Record<string, string>,
      },
    },

    rulesHelper: {
      title: 'Rules helper',
      fromCollectionLabel: 'From my collection',
      collectionDropdownPlaceholder: 'Pick a game…',
      gameNamePlaceholder: 'Type a game name…',
      topicsLabel: 'What aspect? (pick any)',
      topicOptions: [
        'Setup',
        'Basic rules',
        'Special rules',
        'Scoring',
        'Variants',
        'FAQ',
      ] as const,
      questionLabel: 'Your specific question',
      questionPlaceholder: 'e.g. Can you move through other players?',
      promptParts: {
        intro: (game: string) => (game ? `Rules question for ${game}.` : 'Rules question.'),
        topics: (ts: string[]) => `Topic: ${ts.join(', ')}.`,
        question: (q: string) => q,
      },
    },
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
    network: 'No internet connection. Please check your connection.',
    auth: {
      invalidCredentials: 'Invalid email or password.',
      emailInUse: 'This email address is already in use.',
      weakPassword: 'Password must be at least 6 characters.',
      tooManyRequests: 'Too many attempts. Please try again later.',
    },
    assistant: {
      unavailable: 'Assistant is unavailable. Please try again.',
    },
  },
} as const;
